Add support for both python2 str and python3 bytes
aquach/vim-mediawiki-editor pull request #17
Opened 2018-10-23 07:09 UTC by yysfire

I am sorry for [last pull request](https://github.com/aquach/vim-mediawiki-editor/pull/16) which may cause exception in python2. This pull request is a better solution.

2018-10-24 16:53 UTC, alex-quach-ck approved these changes

2018-10-24 16:53 UTC, alex-quach-ck requested changes
Is there a way to do this without using an external library like `six`?

2018-10-25 06:29 UTC, yysfire commented
@alex-quach-ck `mwclient` depend on `six`. `six` will be installed too when `mwclient` is installed.

2018-10-25 16:34 UTC, alex-quach-ck approved these changes
Good call, thanks!

2018-10-26 05:25 UTC, merged